### ISSUE TITLE
The purpose of the self.distr_args(rnn_outputs)

### ISSUE THREAD

**Issue by zf223669** [zalandoresearch/pytorch-ts#104]
Hi,
I could not understand  the code "distr_args = self.distr_args(rnn_outputs=rnn_outputs)" in time_grad_network.py, Could you explain more detail about that, what`s that purpose?
Thank you :)

**Comment by kashif** [comment]
I believe the purpose of this was to project the output from the RNN to the conditioning vector length which the conditional denoising diffusion expects... however if the conditional denoising diffusion module expects the vector size to the same as the hidden size of the RNN then yes this part is perhaps not needed, but with this i can control the conditional vector size... hopefully this helps?
