### ISSUE TITLE
ModuleNotFoundError: No module named 'gluonts.torch.modules.distribution_output'

### ISSUE THREAD

**Issue by kousu** [zalandoresearch/pytorch-ts#105]
I did `pip install pytorchts` (getting version 0.6.0) then tried to run the code in [README.md](https://github.com/zalandoresearch/pytorch-ts/blob/62a18cfd0f19fc2247fc7e79e77f44b8dab6c4c9/README.md) but I got

```
Traceback (most recent call last):
  File "/home/kousu/src/ml/./pts-demo.py", line 12, in <module>
    from pts.model.deepar import DeepAREstimator
  File "/home/kousu/.local/lib/python3.10/site-packages/pts/model/deepar/__init__.py", line 1, in <module>
    from .deepar_estimator import DeepAREstimator
  File "/home/kousu/.local/lib/python3.10/site-packages/pts/model/deepar/deepar_estimator.py", line 31, in <module>
    from gluonts.torch.modules.distribution_output import DistributionOutput
ModuleNotFoundError: No module named 'gluonts.torch.modules.distribution_output'
```

It looks like gluonts has [rearranged some things](https://github.com/awslabs/gluon-ts/issues/1575) (and even more since that thread).

**Comment by kashif** [comment]
i see let me fix up the imports for the latest gluonts

**Comment by kousu** [comment]
Thank you :)

I did by best in #106 but I probably missed a bunch.

**Comment by AbhayGoyal** [comment]
Hey, there still seems to be an issue. I was running once of the example scripts and I get the following error. Could someone help me with it?

ModuleNotFoundError: No module named 'gluonts.torch.modules.distribution_output'

**Comment by Johnreidsilver** [comment]
Just ran into this problem too, you have to uninstall pytorchts and then reinstall from github:

pip3 uninstall pytorchts
pip3 install git+https://github.com/zalandoresearch/pytorch-ts@master

**Comment by kashif** [comment]
@AbhayGoyal i am working on updates in the 0.7.0 branch if you want to test them... there these issues are fixed I believe
