### ISSUE TITLE
About the max_target_dimension variable in time_grad_electricity

### ISSUE THREAD

**Issue by zf223669** [zalandoresearch/pytorch-ts#108]
Hi, I have some confusion of the variable "max_target_dimension" in time_grad_electriciy.
I have noticed that the value of the max_target_dimension = 370,  and the dataset_train contains the target value which is [370,5833], does it mean that the 370 represents the 370 clients and each has 5833 values? however, I saw the fea_static_cat = 1.
above is confusing me?
could someone explain to me?

**Comment by kashif** [comment]
max_target_dimension Is the multivariate dimension, which for this dataset is 370, and since we are considering all the 370 time series at once, this dataset therefore consists of only a single multivariate time serie and that is why it has a single static covariates, I.e. the id of this single multivariate time serie 

hope that helps?

**Comment by zf223669** [comment]
Whether 370 represents the power consumption of different users, they have no correlation.
I saw the dataset on the website said:" This data set contains electricity consumption of 370 points/clients."
Further more, This variable is used to distinguish between different clients, right?

**Comment by kashif** [comment]
In the univariate case we can distinguish between the different time series, however in the multivariate case as in this method we let the model figure it out

**Comment by zf223669** [comment]
> 
thanks，would I like to ask another question?
what's the past_target_CDF and future_target_CDC meaning? Is it provided by the original dataset? Or do I have to recalculate, I can't find anywhere in the code to compute these two variables

**Comment by kashif** [comment]
this is a remnant of some older experiment... at the moment it just renames the variable past_target to past_target_CDF and future_target to future_target_CDF nothing more... so for your information it is essentially the context window target multivariate matrix and prediction window multivariate matrix

**Comment by zf223669** [comment]
THANKS!:)
