### ISSUE TITLE
RuntimeError: input.size(-1) must be equal to input_size. Expected 43, got 19

### ISSUE THREAD

**Issue by nguyend** [zalandoresearch/pytorch-ts#109]
Hi Team,
I've got this error trying to run the example AMZN ticker symbol.
Either from pip install or source still has the same issue.
Please have a look.
Thanks

**Comment by kashif** [comment]
thanks! fixed in the readme

**Comment by nguyend** [comment]
Thanks for fixing the readme.
Could you please explain a bit more how to calculate input_size and what is it?
It depends on prediction_length, e.g.  prediction_length = 6, input_size expected is 12; prediction_length = 12, input_size expected is 14 
but I'm not sure how to get correct input_size if not looking into the exception.
Thanks

**Comment by kashif** [comment]
so in the univariate case we can create batches of a certain temporal length say T of shape: [B, T, 1]

however time series are more than a sequence of numbers as you know and we can potentially add temporal features, static and dynamic covariates from the data and that ends up being contacted to the target tensor in the last dim (feature dim) so we end up with [B, T, F] the F is the input_size (i.e. the size the RNN expects as input). See the deepAR paper on the explanation of the features etc. but hopefully, that clears up what the input_size is...

**Comment by kousu** [comment]
For future ref, see also: #107
