### ISSUE TITLE
No module named 'gluonts.torch.modules.distribution_output'

### ISSUE THREAD

**Issue by sqiual** [zalandoresearch/pytorch-ts#110]
Hi, 
when i tried to run 'from pts.model.time_grad import TimeGradEstimator', I get the error of 'ModuleNotFoundError: No module named 'gluonts.torch.modules.distribution_output''. Can you help me with this issue?

**Comment by kashif** [comment]
perhaps try with the master branch of pytorch-ts...

**Comment by sqiual** [comment]
Thank you. The issue has been solved.
