### ISSUE TITLE
How can TimeGrad be used for univariate dataset?

### ISSUE THREAD

**Issue by BEbillionaireUSD** [zalandoresearch/pytorch-ts#124]
Currently, it seems can only used for multi-variate time series as the Conv1d is conducted on the "metric dim". How can I fix this issue? Thanks!

**Comment by kashif** [comment]
right, I believe for learning the conditional 1-dim distributions there are other choices. If you do not want to assume a parametric distribution class you can use e.g. conditional quantile spline... etc. 

I do not think it makes sense to use diffusion for the 1d case... or am i mistaken?

**Comment by BEbillionaireUSD** [comment]
Yes, I understand. I just want to test different SOTA approaches. TimeGrad works well on multi-variate time series. Thanks for your reply!
