### ISSUE TITLE
How can I use DeepAR in multi-variate dataset

### ISSUE THREAD

**Issue by BEbillionaireUSD** [zalandoresearch/pytorch-ts#125]
I have a customized dataset similar to the data in Multivariate-Flow-Solar (example code), which is in the form of:
``dataset = ListDataset(["target": np.ones(20, 100),"start": ...], one_dim_target=False)``, where 20 denotes the number of columns.

I am wondering how to use DeepAR to predict on my own dataset considering the DeepAREstimator doesn't have a parameter like target_dim?

Looking forward to your help. Thanks!

**Comment by kashif** [comment]
@BEbillionaireUSD i believe deepAR is also a univariate method, and its multivariate variant is called DeepVAR. You can use the implementation of deepVAR here or from gluonts directly which also has an implementation.

**Comment by BEbillionaireUSD** [comment]
Thanks very much for your prompt response! DeepVAR works.
