### ISSUE TITLE
Module Import Issue in Version 0.70

### ISSUE THREAD

**Issue by c1adrien** [zalandoresearch/pytorch-ts#172]
First of all, thank you for your amazing work. I tried running the example from the README in the main branch, but I encountered the following error (when executing the estimator):

```diff
- Exception: Reached maximum number of idle transformation calls. This means the transformation looped over 1 inputs without returning any output. 
```

Following the issues that have been opened about this error, I switched to version 0.70 and tried the TimeGrad example. However, the code tries to import `Trainer` from `pts`, along with several other modules, which causes an error. Is this expected?

Thank you for your assistance.

**Comment by starry-ZRY** [comment]
Did you resolve the issue?
- Exception: Reached maximum number of idle transformation calls. This means the transformation looped over 1 inputs without returning any output.

**Comment by c1adrien** [comment]
No, unfortunately in version 0.70 I don't even reach that error. I get the error I mentioned before even being able to start the training.

**Comment by kashif** [comment]
@c1adrien can you mention the issue with version 0.7.0 branch?

**Comment by c1adrien** [comment]
@starry-ZRY Yes! You can install the solution proposed by https://github.com/LemonCANDY42/pytorch-ts/tree/dev/kenny and make sure you have version 0.12 of `GluonTS`!
 @kashif I'll take care of that !
