### ISSUE TITLE
Cannot import because of tensorboard error, yet tensorboard is installed

### ISSUE THREAD

**Issue by AlexMRuch** [zalandoresearch/pytorch-ts#22]
I have a fresh install of `pytorchts` in it's own environment on my Ubuntu 18 machine, but am unable to import it because of a tensorboard logging issue despite the fact that I have tensorboard installed. 

*Tensorboard, PyTorch, and PyTorchTS versions*
```
(timeseries) amruch@wit:~/graphika/SBIR_COVID$ conda list | grep "board"
tensorboard               2.2.1              pyh532a8cf_0
tensorboard-plugin-wit    1.6.0                      py_0
(timeseries) amruch@wit:~/graphika/SBIR_COVID$ conda list | grep "torch"
pytorch                   1.6.0           py3.6_cuda10.1.243_cudnn7.6.3_0    pytorch
pytorchts                 0.2.0                    pypi_0    pypi
torchvision               0.7.0                py36_cu101    pytorch
```

Error thrown when importing various `pts` modules:
```
(timeseries) amruch@wit:~/graphika/SBIR_COVID$ python
Python 3.6.10 |Anaconda, Inc.| (default, May  8 2020, 02:54:21)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pts.dataset import ListDataset
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/amruch/anaconda3/envs/timeseries/lib/python3.6/site-packages/pts/__init__.py", line 6, in <module>
    from .trainer import Trainer
  File "/home/amruch/anaconda3/envs/timeseries/lib/python3.6/site-packages/pts/trainer.py", line 7, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "/home/amruch/anaconda3/envs/timeseries/lib/python3.6/site-packages/torch/utils/tensorboard/__init__.py", line 4, in <module>
    raise ImportError('TensorBoard logging requires TensorBoard version 1.15 or above')
ImportError: TensorBoard logging requires TensorBoard version 1.15 or above
>>> from pts.model.deepar import DeepAREstimator
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/amruch/anaconda3/envs/timeseries/lib/python3.6/site-packages/pts/__init__.py", line 6, in <module>
    from .trainer import Trainer
  File "/home/amruch/anaconda3/envs/timeseries/lib/python3.6/site-packages/pts/trainer.py", line 7, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "/home/amruch/anaconda3/envs/timeseries/lib/python3.6/site-packages/torch/utils/tensorboard/__init__.py", line 4, in <module>
    raise ImportError('TensorBoard logging requires TensorBoard version 1.15 or above')
ImportError: TensorBoard logging requires TensorBoard version 1.15 or above```

It seems to me that preventing any kind of import due to tensorboard is a bit overkill. Why not just throw a warning that progress/results cannot be logged?

**Comment by kashif** [comment]
right this warning is coming from pytorch... in any case can you kindly try to update:

```
pip install -U tensorboard tensorboard-plugin-wit
```

and try again? Thanks!

**Comment by AlexMRuch** [comment]
I think this has to do with a pip vs. conda install. Your pip install defaults to CPU-only pytorch (why not detect cuda presence and do something like `pip install torch==#.#.#+cu###`), and I tend to use conda to install DL libraries. Do you all have a conda yaml up yet for conda-forge?

**Comment by AlexMRuch** [comment]
Yeah, trying to fix it now with a pip install of the above. Gosh, pip and conda are always such a labyrinth even with brand new envs...

**Comment by AlexMRuch** [comment]
Okay, using the pip version for everything across the board works. So a break happens if you have `conda` pytorch and not `pip` pytroch. So I guess if one wants GPUs for PyTorchTS they should make sure to 1) create a new conda env, 2) conda install `pip`, 2) `pip` install their appropriate GPU version of PyTorch, 3) and finally pip install pytorchts. Hope that helps anyone else hitting this!

**Comment by kashif** [comment]
thanks @AlexMRuch I appreciate you using this library.

**Comment by AlexMRuch** [comment]
Oh, I super appreciate you all making this happen, @kashif! There are so many DL time series models out there but it doesn't seem like many people are really integrating all those into an abstract and generalizable library. Super happy to have stumbled upon it!
