### ISSUE TITLE
data format - from pandas to gluonts data format for both uni-variate and multivariate data

### ISSUE THREAD

**Issue by andrewcztrack** [zalandoresearch/pytorch-ts#27]
Hi @kashif 

I hope your well!
I am just trying to get familiar with the library and I generally work with the pandas data format.
Could you help me format my data and create a basic uni-variate model for prediction into the future.

```python
import numpy as np

import pandas as pd
import yfinance as yf
data = yf.download("SPY", start="2012-01-01", end="2017-04-30")['Adj Close']
data=pd.DataFrame(data)
data

from gluonts.dataset.common import ListDataset
training_data = ListDataset(
    [{"start": data.index[0], "target": data.values[:1300]}],
    freq = "1D"
)

from gluonts.dataset.common import ListDataset
test_data = ListDataset(
    [{"start": data.index[1301], "target": data.values[1301:1339]}],
    freq = "1D"
)


from gluonts.model.simple_feedforward import SimpleFeedForwardEstimator
from gluonts.mx.trainer import Trainer

estimator = SimpleFeedForwardEstimator(
    num_hidden_dimensions=[10],
    prediction_length=38,
    context_length=100,
    freq='1D',
    trainer=Trainer(ctx="cpu", 
                    epochs=5, 
                    learning_rate=1e-3, 
                    num_batches_per_epoch=100
                   )
)
predictor = estimator.train(training_data=training_data)

```

**Comment by kashif** [comment]
@andrewcztrack what is the error that you get? 

Just lookng at this the only thing I can see is that the test dataset has to be essentially the same as the training one with just more extra dates (and not just a time series with the extra dates) 

```
test_data = ListDataset(
    [{"start": data.index[0], "target": data.values]}],
    freq = "1D"
)
```

**Comment by andrewcztrack** [comment]
Hi @kashif i am training on say the previous 1300 points and then predicting on the next 30 points.

**Comment by andrewcztrack** [comment]
for just a basic univariate series and i generally use pandas as the data format.

So basically formatting the data is the hard part.

the error i am getting

  0%|          | 0/100 [00:00<?, ?it/s]
learning rate from ``lr_scheduler`` has been overwritten by ``learning_rate`` in optimizer.

---------------------------------------------------------------------------
GluonTSDataError                          Traceback (most recent call last)
<ipython-input-5-38eacc81e9ea> in <module>
     10                    )
     11 )
---> 12 predictor = estimator.train(training_data=training_data)

~/miniconda3/envs/myenv1/lib/python3.8/site-packages/gluonts/model/estimator.py in train(self, training_data, validation_data, num_workers, num_prefetch, shuffle_buffer_length, **kwargs)
    268         **kwargs,
    269     ) -> Predictor:
--> 270         return self.train_model(
    271             training_data,
    272             validation_data,

~/miniconda3/envs/myenv1/lib/python3.8/site-packages/gluonts/model/estimator.py in train_model(self, training_data, validation_data, num_workers, num_prefetch, shuffle_buffer_length, **kwargs)
    243             trained_net = self.create_training_network()
    244 
--> 245         self.trainer(
    246             net=trained_net,
    247             input_names=get_hybrid_forward_input_names(trained_net),

~/miniconda3/envs/myenv1/lib/python3.8/site-packages/gluonts/mx/trainer/_base.py in __call__(self, net, input_names, train_iter, validation_iter)
    326                     )
    327 
--> 328                     epoch_loss = loop(epoch_no, train_iter)
    329                     if is_validation_available:
    330                         epoch_loss = loop(

~/miniconda3/envs/myenv1/lib/python3.8/site-packages/gluonts/mx/trainer/_base.py in loop(epoch_no, batch_iter, is_training)
    240 
    241                     with tqdm(batch_iter) as it:
--> 242                         for batch_no, data_entry in enumerate(it, start=1):
    243                             if self.halt:
    244                                 break

~/miniconda3/envs/myenv1/lib/python3.8/site-packages/tqdm/std.py in __iter__(self)
   1128 
   1129         try:
-> 1130             for obj in iterable:
   1131                 yield obj
   1132                 # Update and possibly print the progressbar.

~/miniconda3/envs/myenv1/lib/python3.8/site-packages/gluonts/dataset/loader.py in __iter__(self)
    263 
    264     def __iter__(self):
--> 265         yield from itertools.islice(
    266             self.batch_iterator, self.num_batches_per_epoch
    267         )

~/miniconda3/envs/myenv1/lib/python3.8/site-packages/gluonts/dataset/util.py in get_batch()
    161 
    162     def get_batch():
--> 163         return list(take(it, batch_size))
    164 
    165     # has an empty list so that we have a 2D array for sure

~/miniconda3/envs/myenv1/lib/python3.8/site-packages/gluonts/transform/dataset.py in __iter__(self)
     51 
     52     def __iter__(self) -> Iterator[DataEntry]:
---> 53         yield from self.transformation(
     54             self.base_dataset, is_train=self.is_train
     55         )

~/miniconda3/envs/myenv1/lib/python3.8/site-packages/gluonts/transform/_base.py in __call__(self, data_it, is_train)
    130     ) -> Iterator:
    131         num_idle_transforms = 0
--> 132         for data_entry in data_it:
    133             num_idle_transforms += 1
    134             try:

~/miniconda3/envs/myenv1/lib/python3.8/site-packages/gluonts/transform/_base.py in __call__(self, data_it, is_train)
     81         self, data_it: Iterable[DataEntry], is_train: bool
     82     ) -> Iterator:
---> 83         for data_entry in data_it:
     84             try:
     85                 yield self.map_transform(data_entry.copy(), is_train)

~/miniconda3/envs/myenv1/lib/python3.8/site-packages/gluonts/dataset/loader.py in __iter__(self)
     38     def __iter__(self):
     39         while True:
---> 40             yield from self.iterable
     41 
     42 

~/miniconda3/envs/myenv1/lib/python3.8/site-packages/gluonts/dataset/common.py in __iter__(self)
    254 
    255             data = data.copy()
--> 256             data = self.process(data)
    257             data["source"] = SourceContext(source=source_name, row=row_number)
    258             yield data

~/miniconda3/envs/myenv1/lib/python3.8/site-packages/gluonts/dataset/common.py in __call__(self, data)
    455     def __call__(self, data: DataEntry) -> DataEntry:
    456         for t in self.trans:
--> 457             data = t(data)
    458         return data
    459 

~/miniconda3/envs/myenv1/lib/python3.8/site-packages/gluonts/dataset/common.py in __call__(self, data)
    381 
    382             if self.req_ndim != value.ndim:
--> 383                 raise GluonTSDataError(
    384                     f"Array '{self.name}' has bad shape - expected "
    385                     f"{self.req_ndim} dimensions, got {value.ndim}."

GluonTSDataError: Array 'target' has bad shape - expected 1 dimensions, got 2.

**Comment by kashif** [comment]
right so the the "target" has to be a just a 1-dim array of values when you construct the `ListDataset` where each entry is the value at the next `freq` interval

**Comment by andrewcztrack** [comment]
Hi @kashif !! excellent! yes so it would be a 1 dimensional arrary.
so I would i construct that using the data structures.

**Comment by andrewcztrack** [comment]
Hi @kashif ! my laptop is about to die.
can I touch base in a few hours.
Kind regards and thanks,
Andrew

**Comment by andrewcztrack** [comment]
Hi @kashif !! I hope your well.
Would you possibly have some time to assist.
Kind regards and thanks,
Andrew

**Comment by andrewcztrack** [comment]
I am trying to set up a base forecasting experiment. starting with a single pandas dataframe and then looking at a multivariate case.
Best,
Andrew

**Comment by kashif** [comment]
I would snuggest yes just go through the tutorials and make an issue if you get stuck or something does not work

**Comment by andrewcztrack** [comment]
Hi @kashif  I had a look at the examples but a lot of the examples are with dataset already with the package.
I was having a look at using custom datasets but I am getting stuck on the error

# train dataset: cut the last window of length "prediction_length", add "target" and "start" fields
train_ds = ListDataset([{'target': x, 'start': start}
                        for x in custom_dataset[:, :-prediction_length]],
                       freq=freq)
# test dataset: use the whole dataset, add "target" and "start" fields
test_ds = ListDataset([{'target': x, 'start': start}
                       for x in custom_dataset],
                      freq=freq)

How would i adapt the above to a single pandas dataframe

**Comment by kashif** [comment]
@andrewcztrack you just make a list of dicts with `"target": [1, 4,2, ....]` and `"start"` being the start date and this list you use to instantiate the  `train_ds = ListDataset(...)` So just loop over you pandas dataframe assuming it has multiple time series and for each time series just make the target and start dictonary....

**Comment by andrewcztrack** [comment]
hi @kashif ! I hope your well. is the below correct?


```python

import numpy as np
prediction_length = 24
freq = "1D"
import pandas as pd
import yfinance as yf
data = yf.download("SPY", start="2012-01-01", end="2017-04-30")['Adj Close']
data=pd.DataFrame(data)
custom_dataset=data.to_numpy()
start=custom_dataset[0]

train_ds = ListDataset([{'target': custom_dataset, 'start': start},
                            custom_dataset[:, :-prediction_length]],
                       freq=freq)
# test dataset: use the whole dataset, add "target" and "start" fields
test_ds = ListDataset([{'target': custom_dataset, 'start': start},
                           custom_dataset],
                      freq=freq)

```
