### ISSUE TITLE
how to customize dataset?

### ISSUE THREAD

**Issue by bugsuse** [zalandoresearch/pytorch-ts#31]
It's a great work! And I want to apply the model to predict air quality such as PM10 and PM2.5 based on temperature, wind speed and direction and so on. Can this model directly accept pytorch's dataloader object? If not, how to customize dataset?

**Comment by kashif** [comment]
@bugsuse thanks! So you need to convert your data to the actual format the models accept. Have a look at the `_m5` data set file where I prepare such a dataset. Once you have a dataset we do use PyTorch `DataLoaders` to make batches etc.

**Comment by bugsuse** [comment]
@kashif Thanks so much! I have solved it and closed it.
