### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by harshilkamdar** [zalandoresearch/pytorch-ts#38]
Hi, with the latest update of making gluonts a requirement, I think there seems to be an issue with the installation via pip. 

The error I get: 

ERROR: Packages installed from PyPI cannot depend on packages which are not also hosted on PyPI.
pytorchts depends on gluonts@ git+https://github.com/awslabs/gluon-ts.git@master#egg=gluonts

**Comment by kashif** [comment]
ah damn! Yes that will not works... hmmm ok for now kindly first install:

```
pip install git+https://github.com/awslabs/gluon-ts.git@master#egg=gluonts
```

and then:

```
pip install pytorchts
```

till I can figure out how to fix this.

**Comment by harshilkamdar** [comment]
Huh, not sure if this is an issue on pytorch-ts's end, but when I try to install gluonts with the method above, I get the error:

ContextualVersionConflict: (pydantic 1.7.3 (/opt/conda/lib/python3.7/site-packages), Requirement.parse('pydantic<1.7,~=1.1'), {'gluonts'})

It seems to be installing the right version of pydantic but some conda issues? not sure.

**Comment by kashif** [comment]
I see and if you remove your `pydantic ` first via:

```
pip uninstall pydantic
```

and then try to install gluonts via the command above does it work?

**Comment by harshilkamdar** [comment]
No, didn't work. I'm on a cloud-hosted notebook, so that might be the issue. Thank you for the great package!

**Comment by kashif** [comment]
I see, and how about if you install the 1.6.1 version via: `pip install pydantic==1.6.1` and then glutonts?

**Comment by fernandocamargoti** [comment]
I don't this project specify the gluonts version using pip instead of the master branch? Like:
gluonts>=0.6.7

**Comment by kashif** [comment]
@fernandocamargoti some of my fixes to gluonts are still in master so as soon as a new version comes I will update it here.

**Comment by fernandocamargoti** [comment]
Oh, understood. Thanks for the update.

By the way, I installed it with:

`pip install --no-deps pytorchts==0.3.1`
