### ISSUE TITLE
Issue with fourier time-series features at weekly frequency

### ISSUE THREAD

**Issue by nsoma97** [zalandoresearch/pytorch-ts#41]
Hey!

My pandas version is 1.1.0. In `pts/feature/fourier_date_feature.py` on line 52, `pandas.tseries.frequencies.to_offset` is used to normalize frequency, but when the `freq_str` parameter is `W` this function produces the following:

```python
offset = to_offset('W')
multiple, granularity = offset.n, offset.name

print(granularity)
# this prints 'W-SUN' which is equivalent to 'W'
```

Because of the assertion on line 66, `W-SUN` and thus the initial `W` is not accepted. Changing `W` to `W-SUN` in the `features` dictionary (or adding both) had fixed this issue for me.

Thanks for looking into this.

**Comment by kashif** [comment]
thanks @nsoma97 fixed!

**Comment by nsoma97** [comment]
Awesome, thank you!
