### ISSUE TITLE
Tweedie Loss

### ISSUE THREAD

**Issue by Akaori** [zalandoresearch/pytorch-ts#48]
Is it possible to add this distribution to deepAR model ?

https://discuss.pytorch.org/t/custom-tweedie-loss-throwing-an-error-in-pytorch/76349/6

**Comment by kashif** [comment]
so you can use the zero inflated possion or zero inflated negative binomial output distributions which are implemented

**Comment by Akaori** [comment]
Sounds good, tks @kashif
