### ISSUE TITLE
have a problem on ubuntu example

### ISSUE THREAD

**Issue by xtyi1997** [zalandoresearch/pytorch-ts#57]
dataset:url = "https://raw.githubusercontent.com/numenta/NAB/master/data/realTweets/Twitter_volume_AMZN.csv"
example=https://github.com/zalandoresearch/pytorch-ts

---------------------------------------------------------------------------

RuntimeError                              Traceback (most recent call last)

<ipython-input-36-cfa2549df192> in <module>
      7                                             device=device))
      8 # predictor = estimator.train(training_data=training_data, num_workers=4)
----> 9 predictor = estimator.train(training_data=training_data, num_workers=1)
     10 

~/Documents/pytorch-ts/pts/model/estimator.py in train(self, training_data, validation_data, num_workers, prefetch_factor, shuffle_buffer_length, cache_data, **kwargs)
    179             shuffle_buffer_length=shuffle_buffer_length,
    180             cache_data=cache_data,
--> 181             **kwargs,
    182         ).predictor

~/Documents/pytorch-ts/pts/model/estimator.py in train_model(self, training_data, validation_data, num_workers, prefetch_factor, shuffle_buffer_length, cache_data, **kwargs)
    147             net=trained_net,
    148             train_iter=training_data_loader,
--> 149             validation_iter=validation_data_loader,
    150         )
    151 

~/Documents/pytorch-ts/pts/trainer.py in __call__(self, net, train_iter, validation_iter)
     70 
     71                     inputs = [v.to(self.device) for v in data_entry.values()]
---> 72                     output = net(*inputs)
     73 
     74                     if isinstance(output, (list, tuple)):

~/anaconda3/envs/torch18/lib/python3.6/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    887             result = self._slow_forward(*input, **kwargs)
    888         else:
--> 889             result = self.forward(*input, **kwargs)
    890         for hook in itertools.chain(
    891                 _global_forward_hooks.values(),

~/Documents/pytorch-ts/pts/model/deepar/deepar_network.py in forward(self, feat_static_cat, feat_static_real, past_time_feat, past_target, past_observed_values, future_time_feat, future_target, future_observed_values)
    252             future_time_feat=future_time_feat,
    253             future_target=future_target,
--> 254             future_observed_values=future_observed_values,
    255         )
    256 

~/Documents/pytorch-ts/pts/model/deepar/deepar_network.py in distribution(self, feat_static_cat, feat_static_real, past_time_feat, past_target, past_observed_values, future_time_feat, future_target, future_observed_values)
    226             past_observed_values=past_observed_values,
    227             future_time_feat=future_time_feat,
--> 228             future_target=future_target,
    229         )
    230 

~/Documents/pytorch-ts/pts/model/deepar/deepar_network.py in unroll_encoder(self, feat_static_cat, feat_static_real, past_time_feat, past_target, past_observed_values, future_time_feat, future_target)
    198 
    199         # unroll encoder
--> 200         outputs, state = self.rnn(inputs)
    201 
    202         # outputs: (batch_size, seq_len, num_cells)

~/anaconda3/envs/torch18/lib/python3.6/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    887             result = self._slow_forward(*input, **kwargs)
    888         else:
--> 889             result = self.forward(*input, **kwargs)
    890         for hook in itertools.chain(
    891                 _global_forward_hooks.values(),

~/anaconda3/envs/torch18/lib/python3.6/site-packages/torch/nn/modules/rnn.py in forward(self, input, hx)
    657             hx = self.permute_hidden(hx, sorted_indices)
    658 
--> 659         self.check_forward_args(input, hx, batch_sizes)
    660         if batch_sizes is None:
    661             result = _VF.lstm(input, hx, self._flat_weights, self.bias, self.num_layers,

~/anaconda3/envs/torch18/lib/python3.6/site-packages/torch/nn/modules/rnn.py in check_forward_args(self, input, hidden, batch_sizes)
    603     # See torch/nn/modules/module.py::_forward_unimplemented
    604     def check_forward_args(self, input: Tensor, hidden: Tuple[Tensor, Tensor], batch_sizes: Optional[Tensor]):  # type: ignore
--> 605         self.check_input(input, batch_sizes)
    606         self.check_hidden_size(hidden[0], self.get_expected_hidden_size(input, batch_sizes),
    607                                'Expected hidden[0] size {}, got {}')

~/anaconda3/envs/torch18/lib/python3.6/site-packages/torch/nn/modules/rnn.py in check_input(self, input, batch_sizes)
    202             raise RuntimeError(
    203                 'input.size(-1) must be equal to input_size. Expected {}, got {}'.format(
--> 204                     self.input_size, input.size(-1)))
    205 
    206     def get_expected_hidden_size(self, input: Tensor, batch_sizes: Optional[Tensor]) -> Tuple[int, int, int]:

RuntimeError: input.size(-1) must be equal to input_size. Expected 43, got 19

**Comment by kashif** [comment]
right can you try with `input_size=19`?

**Comment by xtyi1997** [comment]
> right can you try with `input_size=19`?

it work for me
