### ISSUE TITLE
AttributeError: 'TempFlowTrainingNetwork' object has no attribute '_wandb_hook_names'

### ISSUE THREAD

**Issue by honglinwen** [zalandoresearch/pytorch-ts#59]
After your update of Trainer, it will report the bug when I run your example.

I found that you have added wandb in the trainer.

**Comment by honglinwen** [comment]
> After your update of Trainer, it will report the bug when I run your example.
> 
> I found that you have added wandb in the trainer.

Actually, the deepAR example also reports this bug.

**Comment by kashif** [comment]
the issue is with `wandb` it seems as it was working previously...

**Comment by kashif** [comment]
@honglinwen can you try with: `pip install wandb==0.10.32`

**Comment by honglinwen** [comment]
> @honglinwen can you try with: `pip install wandb==0.10.32`

Thanks for the reply. I also think it is worthwhile to try to fix the version of _wandb_

**Comment by vpozdnyakov** [comment]
@kashif hi, unfortunately installing 0.10.32 doesn't help
![image](https://user-images.githubusercontent.com/12996098/124309821-fe5a8800-db73-11eb-966d-ed3605d75b58.png)

**Comment by kashif** [comment]
This is the issue on the wandb side: https://github.com/wandb/client/issues/2349

**Comment by kashif** [comment]
I've removed wandb in the new version
