### ISSUE TITLE
prefetch_factor problem

### ISSUE THREAD

**Issue by zzqCool** [zalandoresearch/pytorch-ts#81]
I run the code in example file folder, but they are all report the error, that is "_init__() got an unexpected keyword argument 'prefetch_factor'“，and my pytorchts version is 0.5.1
![error](https://user-images.githubusercontent.com/51504872/142765157-b36ed69f-41f4-4a61-937b-bfef8ffbda8c.jpeg)

**Comment by kashif** [comment]
@zzqCool which version of torch are you using?

**Comment by zzqCool** [comment]
Thaky you remind, before I update the version of torch, its version is 1.6.0, and now is 1.10.0 so the error message is disappear

**Comment by zzqCool** [comment]
> @zzqCool which version of torch are you using?

Thank you your remind, before I update the version of torch, its version is 1.6.0, and now is 1.10.0 so the error message is disappear

**Comment by zzqCool** [comment]
@kashif Thank you your remind, before I update the version of torch, its version is 1.6.0, and now is 1.10.0 so the error message is disappear
